const developers = [
  {
    first_name: 'Isaias',
    last_name: 'Mraz',
    image_url: 'https://cdn.fakercloud.com/avatars/_yardenoon_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 4,
    rating: 5,
    super_powers: ['WebLogic', 'Backbone.js'],
    technologies: [
      'AngularJS',
      'ASP.NET Web API',
      'React.js',
      'Handlebars.js',
      'Meteor.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 0,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Trystan',
    last_name: 'Ratke',
    image_url: 'https://cdn.fakercloud.com/avatars/liminha_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 5.5,
    rating: 5,
    super_powers: ['Require.js', 'Node.js'],
    technologies: ['Meteor.js', 'Ext JS', 'Web Analytics', 'D3.js', 'Web 2.0'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 1,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Merl',
    last_name: 'Klocko',
    image_url: 'https://cdn.fakercloud.com/avatars/nessoila_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 9.4,
    rating: 3,
    super_powers: ['Web Applications', 'Web 2.0'],
    technologies: [
      'Bootstrap',
      'Web Design',
      'Ember.js',
      'Node.js',
      'J2EE Web Services',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 2,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Declan',
    last_name: 'Weber',
    image_url: 'https://cdn.fakercloud.com/avatars/craighenneberry_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud System Engineer',
    years_of_experience: 6.3,
    rating: 5,
    super_powers: ['D3.js', 'Express.js'],
    technologies: ['Ext JS', 'Backbone.js', 'Express.js', 'Node.js', 'Web 2.0'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 3,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Rey',
    last_name: 'Koss',
    image_url: 'https://cdn.fakercloud.com/avatars/adamawesomeface_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 9.1,
    rating: 3,
    super_powers: ['WebLogic', 'Meteor.js'],
    technologies: [
      'Vue.js',
      'Web Video',
      'JavaScript',
      'Bootstrap',
      'Web Services',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 4,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Opal',
    last_name: 'Bauch',
    image_url: 'https://cdn.fakercloud.com/avatars/sunlandictwin_128.jpg',
    country_code: 'PT',
    job_position: 'Systems Analyst',
    years_of_experience: 8.1,
    rating: 5,
    super_powers: ['Web 2.0', 'Ember.js'],
    technologies: [
      'J2EE Web Services',
      'Require.js',
      'Vue.js',
      'Express.js',
      'JSON',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 5,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Sheila',
    last_name: 'Rice',
    image_url: 'https://cdn.fakercloud.com/avatars/prinzadi_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 9.3,
    rating: 3,
    super_powers: ['Web Services', 'Jakarta EE'],
    technologies: [
      'Web Services API',
      'Web 2.0',
      'Require.js',
      'JSON',
      'Vue.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 6,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Lenna',
    last_name: 'Rath',
    image_url: 'https://cdn.fakercloud.com/avatars/muringa_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 5.1,
    rating: 5,
    super_powers: ['Web Services', 'Web 2.0'],
    technologies: [
      'Node.js',
      'Ember.js',
      'Web Development',
      'Web Analytics',
      'Vue.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 7,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Zachery',
    last_name: 'McGlynn',
    image_url: 'https://cdn.fakercloud.com/avatars/joshuaraichur_128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 6.9,
    rating: 4,
    super_powers: ['Web Applications', 'Handlebars.js'],
    technologies: [
      'Web Design',
      'Handlebars.js',
      'Social Media',
      'Vue.js',
      'Require.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 8,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Lavina',
    last_name: 'Huel',
    image_url: 'https://cdn.fakercloud.com/avatars/LucasPerdidao_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 3.1,
    rating: 5,
    super_powers: ['Ember.js', 'Web Services API'],
    technologies: [
      'JavaScript',
      'Bootstrap',
      'J2EE Web Services',
      'WebLogic',
      'D3.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 9,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Marcella',
    last_name: 'Osinski',
    image_url: 'https://cdn.fakercloud.com/avatars/fjaguero_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 0.1,
    rating: 5,
    super_powers: ['Web Analytics', 'Jakarta EE'],
    technologies: [
      'Web 2.0',
      'Web Applications',
      'Bootstrap',
      'Handlebars.js',
      'Web Analytics',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 10,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Meta',
    last_name: 'Labadie',
    image_url: 'https://cdn.fakercloud.com/avatars/agromov_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud System Engineer',
    years_of_experience: 8.4,
    rating: 3,
    super_powers: ['Express.js', 'Web Applications'],
    technologies: [
      'Vue.js',
      'ASP.NET Web API',
      'Web Development',
      'Gulp.js',
      'Web Analytics',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 11,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Irma',
    last_name: 'Johnson',
    image_url: 'https://cdn.fakercloud.com/avatars/vlajki_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 8.5,
    rating: 3,
    super_powers: ['Jakarta EE', 'Express.js'],
    technologies: [
      'JavaScript',
      'Jakarta EE',
      'J2EE Web Services',
      'Vue.js',
      'Meteor.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 12,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Neva',
    last_name: 'Abernathy',
    image_url: 'https://cdn.fakercloud.com/avatars/rodnylobos_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 0.7,
    rating: 3,
    super_powers: ['Web Analytics', 'Web Design'],
    technologies: [
      'Ember.js',
      'ASP.NET Web API',
      'Node.js',
      'Social Media',
      'Web Design',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 13,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Lysanne',
    last_name: 'Walsh',
    image_url: 'https://cdn.fakercloud.com/avatars/curiousonaut_128.jpg',
    country_code: 'PT',
    job_position: 'Systems Analyst',
    years_of_experience: 0.4,
    rating: 4,
    super_powers: ['Web Services API', 'Web Applications'],
    technologies: ['WebLogic', 'Web 2.0', 'Ext JS', 'Web Design', 'JSON'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 14,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Dahlia',
    last_name: 'Wuckert',
    image_url: 'https://cdn.fakercloud.com/avatars/shalt0ni_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 6,
    rating: 5,
    super_powers: ['Social Media', 'Vue.js'],
    technologies: [
      'JavaScript',
      'Gulp.js',
      'Web Services',
      'Social Media',
      'Web Design',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 15,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Marcelo',
    last_name: 'Dicki',
    image_url: 'https://cdn.fakercloud.com/avatars/jodytaggart_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud System Engineer',
    years_of_experience: 8.3,
    rating: 5,
    super_powers: ['Ember.js', 'React.js'],
    technologies: [
      'Web Development',
      'Express.js',
      'Redux.js',
      'Web Video',
      'Web Analytics',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 16,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Sheila',
    last_name: 'Gerhold',
    image_url: 'https://cdn.fakercloud.com/avatars/kojourin_128.jpg',
    country_code: 'PT',
    job_position: 'Web Developer',
    years_of_experience: 9.6,
    rating: 4,
    super_powers: ['AngularJS', 'Require.js'],
    technologies: [
      'JavaScript',
      'AngularJS',
      'Bootstrap',
      'Backbone.js',
      'React.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 17,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Dahlia',
    last_name: 'Gusikowski',
    image_url: 'https://cdn.fakercloud.com/avatars/rohixx_128.jpg',
    country_code: 'PT',
    job_position: 'Back End Developer',
    years_of_experience: 5.4,
    rating: 5,
    super_powers: ['Redux.js', 'Web Video'],
    technologies: [
      'Web Applications',
      'Bootstrap',
      'Express.js',
      'Web Development',
      'Web Video',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 18,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Lonzo',
    last_name: 'Daniel',
    image_url: 'https://cdn.fakercloud.com/avatars/felipecsl_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 5.7,
    rating: 3,
    super_powers: ['Web 2.0', 'Web Applications'],
    technologies: [
      'JavaScript',
      'Express.js',
      'Web Development',
      'Meteor.js',
      'Jakarta EE',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 19,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Hazle',
    last_name: 'Ondricka',
    image_url: 'https://cdn.fakercloud.com/avatars/besbujupi_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 9,
    rating: 4,
    super_powers: ['Ember.js', 'Web Video'],
    technologies: [
      'Bootstrap',
      'Web Design',
      'Handlebars.js',
      'Web Applications',
      'Meteor.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 20,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Alysson',
    last_name: 'Parisian',
    image_url: 'https://cdn.fakercloud.com/avatars/stefooo_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 4.1,
    rating: 5,
    super_powers: ['Bootstrap', 'Web Applications'],
    technologies: [
      'Bootstrap',
      'Ext JS',
      'ASP.NET Web API',
      'JavaScript',
      'AngularJS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 21,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Adela',
    last_name: 'Schoen',
    image_url: 'https://cdn.fakercloud.com/avatars/superoutman_128.jpg',
    country_code: 'PT',
    job_position: 'Systems Analyst',
    years_of_experience: 0.4,
    rating: 4,
    super_powers: ['Web Applications', 'Bootstrap'],
    technologies: [
      'Backbone.js',
      'Web Analytics',
      'Web Video',
      'J2EE Web Services',
      'Web Services API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 22,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Emely',
    last_name: 'Nikolaus',
    image_url: 'https://cdn.fakercloud.com/avatars/fotomagin_128.jpg',
    country_code: 'PT',
    job_position: 'Back End Developer',
    years_of_experience: 5.7,
    rating: 5,
    super_powers: ['Vue.js', 'Ext JS'],
    technologies: [
      'Ember.js',
      'JavaScript',
      'Handlebars.js',
      'Web Design',
      'Ext JS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 23,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Quinten',
    last_name: 'Effertz',
    image_url: 'https://cdn.fakercloud.com/avatars/irae_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 6.3,
    rating: 5,
    super_powers: ['Web Analytics', 'Meteor.js'],
    technologies: [
      'Vue.js',
      'Web Applications',
      'JSON',
      'Ember.js',
      'AngularJS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 24,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Pattie',
    last_name: 'Berge',
    image_url: 'https://cdn.fakercloud.com/avatars/charlesrpratt_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 5.4,
    rating: 3,
    super_powers: ['WebLogic', 'Web Design'],
    technologies: ['Bootstrap', 'Web Services', 'D3.js', 'JavaScript', 'JSON'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 25,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Macie',
    last_name: 'Koss',
    image_url: 'https://cdn.fakercloud.com/avatars/madcampos_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 7.9,
    rating: 5,
    super_powers: ['Vue.js', 'Require.js'],
    technologies: [
      'Jakarta EE',
      'Ext JS',
      'Ember.js',
      'Web Development',
      'Require.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 26,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Juanita',
    last_name: 'Sipes',
    image_url: 'https://cdn.fakercloud.com/avatars/demersdesigns_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 9.1,
    rating: 3,
    super_powers: ['Web 2.0', 'Web Services'],
    technologies: [
      'Web Design',
      'Bootstrap',
      'AngularJS',
      'J2EE Web Services',
      'Web Applications',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 27,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Gladys',
    last_name: 'Schimmel',
    image_url: 'https://cdn.fakercloud.com/avatars/abelcabans_128.jpg',
    country_code: 'PT',
    job_position: 'IT Manager',
    years_of_experience: 4.4,
    rating: 4,
    super_powers: ['Social Media', 'Gulp.js'],
    technologies: [
      'Web Analytics',
      'AngularJS',
      'J2EE Web Services',
      'Web Design',
      'Ext JS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 28,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Verla',
    last_name: 'Sipes',
    image_url: 'https://cdn.fakercloud.com/avatars/chaabane_wail_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 5.4,
    rating: 4,
    super_powers: ['Web Services', 'Web 2.0'],
    technologies: [
      'Web Applications',
      'ASP.NET Web API',
      'WebLogic',
      'Backbone.js',
      'Ext JS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 29,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Gideon',
    last_name: 'Frami',
    image_url: 'https://cdn.fakercloud.com/avatars/buddhasource_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 4.5,
    rating: 3,
    super_powers: ['Web Video', 'Handlebars.js'],
    technologies: [
      'WebLogic',
      'D3.js',
      'Web Development',
      'Web Video',
      'Handlebars.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 30,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Joany',
    last_name: 'Graham',
    image_url: 'https://cdn.fakercloud.com/avatars/ehsandiary_128.jpg',
    country_code: 'PT',
    job_position: 'Back End Developer',
    years_of_experience: 4.6,
    rating: 3,
    super_powers: ['Node.js', 'Ext JS'],
    technologies: [
      'D3.js',
      'Backbone.js',
      'Web Services API',
      'Web Video',
      'Require.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 31,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Jamil',
    last_name: 'Dietrich',
    image_url: 'https://cdn.fakercloud.com/avatars/cicerobr_128.jpg',
    country_code: 'PT',
    job_position: 'IT Manager',
    years_of_experience: 5.3,
    rating: 4,
    super_powers: ['Ember.js', 'Jakarta EE'],
    technologies: [
      'Require.js',
      'Social Media',
      'Express.js',
      'D3.js',
      'Ember.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 32,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Karlie',
    last_name: 'Morar',
    image_url: 'https://cdn.fakercloud.com/avatars/polarity_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 5.6,
    rating: 5,
    super_powers: ['Ember.js', 'Require.js'],
    technologies: [
      'Web Development',
      'Web Services API',
      'AngularJS',
      'Bootstrap',
      'D3.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 33,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Alivia',
    last_name: 'Schultz',
    image_url: 'https://cdn.fakercloud.com/avatars/bryan_topham_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud System Engineer',
    years_of_experience: 4.8,
    rating: 5,
    super_powers: ['ASP.NET Web API', 'Web Video'],
    technologies: [
      'Web Services API',
      'React.js',
      'Backbone.js',
      'Web Development',
      'Bootstrap',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 34,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Brad',
    last_name: 'Luettgen',
    image_url: 'https://cdn.fakercloud.com/avatars/nateschulte_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 4.8,
    rating: 4,
    super_powers: ['Handlebars.js', 'React.js'],
    technologies: [
      'WebLogic',
      'React.js',
      'Web Design',
      'Meteor.js',
      'JavaScript',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 35,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Talia',
    last_name: 'Mosciski',
    image_url: 'https://cdn.fakercloud.com/avatars/yayteejay_128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 5.5,
    rating: 4,
    super_powers: ['ASP.NET Web API', 'Social Media'],
    technologies: [
      'Node.js',
      'Web Applications',
      'Web Analytics',
      'Web 2.0',
      'AngularJS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 36,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Pearlie',
    last_name: 'Bartoletti',
    image_url: 'https://cdn.fakercloud.com/avatars/yesmeck_128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 1.5,
    rating: 5,
    super_powers: ['Web Services', 'Ember.js'],
    technologies: [
      'Node.js',
      'Meteor.js',
      'Web 2.0',
      'Web Services API',
      'Web Design',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 37,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Nels',
    last_name: 'Russel',
    image_url: 'https://cdn.fakercloud.com/avatars/xravil_128.jpg',
    country_code: 'PT',
    job_position: 'IT Manager',
    years_of_experience: 8.1,
    rating: 3,
    super_powers: ['Web Design', 'Express.js'],
    technologies: [
      'JavaScript',
      'Web Services API',
      'Web Video',
      'Web Services',
      'Web Development',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 38,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Manuela',
    last_name: 'Donnelly',
    image_url: 'https://cdn.fakercloud.com/avatars/evanshajed_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 2,
    rating: 3,
    super_powers: ['Express.js', 'Require.js'],
    technologies: [
      'Node.js',
      'Backbone.js',
      'Web Video',
      'Handlebars.js',
      'Web Design',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 39,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Darion',
    last_name: 'Kulas',
    image_url: 'https://cdn.fakercloud.com/avatars/mateaodviteza_128.jpg',
    country_code: 'PT',
    job_position: 'IT Manager',
    years_of_experience: 5.1,
    rating: 5,
    super_powers: ['Social Media', 'J2EE Web Services'],
    technologies: [
      'Web Design',
      'ASP.NET Web API',
      'React.js',
      'Social Media',
      'JSON',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 40,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Delphia',
    last_name: 'Kozey',
    image_url: 'https://cdn.fakercloud.com/avatars/cloudstudio_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud System Engineer',
    years_of_experience: 4.2,
    rating: 5,
    super_powers: ['React.js', 'Node.js'],
    technologies: [
      'Web Services',
      'ASP.NET Web API',
      'D3.js',
      'AngularJS',
      'Backbone.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 41,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Gustave',
    last_name: 'Corwin',
    image_url: 'https://cdn.fakercloud.com/avatars/aeon56_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 0.9,
    rating: 3,
    super_powers: ['Node.js', 'JavaScript'],
    technologies: ['JavaScript', 'Ember.js', 'Node.js', 'Ext JS', 'Web 2.0'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 42,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Lea',
    last_name: 'Breitenberg',
    image_url: 'https://cdn.fakercloud.com/avatars/vovkasolovev_128.jpg',
    country_code: 'PT',
    job_position: 'Front End Developer',
    years_of_experience: 0.7,
    rating: 4,
    super_powers: ['Ext JS', 'Web Applications'],
    technologies: [
      'Jakarta EE',
      'Ember.js',
      'Web Applications',
      'Social Media',
      'Backbone.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 43,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Harmon',
    last_name: 'Schroeder',
    image_url: 'https://cdn.fakercloud.com/avatars/coreyhaggard_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 9.5,
    rating: 3,
    super_powers: ['JavaScript', 'Web Services'],
    technologies: ['Redux.js', 'Web 2.0', 'D3.js', 'Vue.js', 'WebLogic'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 44,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Vinnie',
    last_name: 'Stiedemann',
    image_url: 'https://cdn.fakercloud.com/avatars/soyjavi_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 6.3,
    rating: 5,
    super_powers: ['ASP.NET Web API', 'Ember.js'],
    technologies: [
      'Web Analytics',
      'AngularJS',
      'Web Services API',
      'J2EE Web Services',
      'D3.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 45,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Federico',
    last_name: 'Sauer',
    image_url: 'https://cdn.fakercloud.com/avatars/krasnoukhov_128.jpg',
    country_code: 'PT',
    job_position: 'Web Developer',
    years_of_experience: 6.1,
    rating: 5,
    super_powers: ['Node.js', 'Ext JS'],
    technologies: [
      'Web 2.0',
      'Ember.js',
      'Web Services',
      'Web Applications',
      'Web Services API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 46,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Cloyd',
    last_name: 'Prohaska',
    image_url: 'https://cdn.fakercloud.com/avatars/areus_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 2.5,
    rating: 4,
    super_powers: ['Web Analytics', 'Web Development'],
    technologies: [
      'Web 2.0',
      'Meteor.js',
      'Bootstrap',
      'Redux.js',
      'Web Design',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 47,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Petra',
    last_name: 'Kuhlman',
    image_url: 'https://cdn.fakercloud.com/avatars/badlittleduck_128.jpg',
    country_code: 'PT',
    job_position: 'Front End Developer',
    years_of_experience: 6.8,
    rating: 3,
    super_powers: ['Gulp.js', 'Web 2.0'],
    technologies: [
      'Backbone.js',
      'Web Video',
      'Jakarta EE',
      'Ember.js',
      'J2EE Web Services',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 48,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Germaine',
    last_name: 'Rohan',
    image_url: 'https://cdn.fakercloud.com/avatars/falvarad_128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 9.3,
    rating: 3,
    super_powers: ['Require.js', 'ASP.NET Web API'],
    technologies: [
      'Ext JS',
      'Web Design',
      'Web Development',
      'Web Services API',
      'Meteor.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 49,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Harley',
    last_name: 'Terry',
    image_url: 'https://cdn.fakercloud.com/avatars/saschadroste_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 9.4,
    rating: 5,
    super_powers: ['Ext JS', 'Node.js'],
    technologies: [
      'JavaScript',
      'WebLogic',
      'Gulp.js',
      'Social Media',
      'Web Design',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 50,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Mathias',
    last_name: 'Kling',
    image_url: 'https://cdn.fakercloud.com/avatars/devankoshal_128.jpg',
    country_code: 'PT',
    job_position: 'Front End Developer',
    years_of_experience: 3.9,
    rating: 5,
    super_powers: ['Redux.js', 'Web Analytics'],
    technologies: [
      'Bootstrap',
      'Web Services',
      'Web Applications',
      'Web Analytics',
      'Ember.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 51,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Arvel',
    last_name: 'Wisoky',
    image_url: 'https://cdn.fakercloud.com/avatars/saschadroste_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 4.1,
    rating: 3,
    super_powers: ['Social Media', 'Backbone.js'],
    technologies: [
      'Ext JS',
      'J2EE Web Services',
      'Gulp.js',
      'Web Analytics',
      'JSON',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 52,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Lyda',
    last_name: 'Adams',
    image_url: 'https://cdn.fakercloud.com/avatars/praveen_vijaya_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 7.1,
    rating: 5,
    super_powers: ['Node.js', 'Web Applications'],
    technologies: [
      'Jakarta EE',
      'Handlebars.js',
      'Ext JS',
      'Bootstrap',
      'Web Analytics',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 53,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Zoila',
    last_name: 'Shields',
    image_url: 'https://cdn.fakercloud.com/avatars/charliegann_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 6.9,
    rating: 3,
    super_powers: ['Web 2.0', 'J2EE Web Services'],
    technologies: [
      'Web Services',
      'J2EE Web Services',
      'Web Applications',
      'Meteor.js',
      'Node.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 54,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Delta',
    last_name: 'Casper',
    image_url: 'https://cdn.fakercloud.com/avatars/_dwite__128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 2.7,
    rating: 3,
    super_powers: ['Web Services', 'Web Services API'],
    technologies: ['Redux.js', 'D3.js', 'Gulp.js', 'Require.js', 'Bootstrap'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 55,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Lilyan',
    last_name: 'Corwin',
    image_url: 'https://cdn.fakercloud.com/avatars/lingeswaran_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 8,
    rating: 5,
    super_powers: ['Web Analytics', 'Bootstrap'],
    technologies: [
      'Express.js',
      'React.js',
      'Web Services API',
      'Web Applications',
      'WebLogic',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 56,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Alden',
    last_name: 'Funk',
    image_url: 'https://cdn.fakercloud.com/avatars/sebashton_128.jpg',
    country_code: 'PT',
    job_position: 'Web Developer',
    years_of_experience: 9.6,
    rating: 4,
    super_powers: ['AngularJS', 'WebLogic'],
    technologies: [
      'J2EE Web Services',
      'Gulp.js',
      'Express.js',
      'Web Services API',
      'Bootstrap',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 57,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Brad',
    last_name: 'Macejkovic',
    image_url: 'https://cdn.fakercloud.com/avatars/adobi_128.jpg',
    country_code: 'PT',
    job_position: 'Front End Developer',
    years_of_experience: 6.8,
    rating: 4,
    super_powers: ['Ext JS', 'J2EE Web Services'],
    technologies: [
      'Web Applications',
      'React.js',
      'JavaScript',
      'Social Media',
      'Redux.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 58,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Ashlynn',
    last_name: 'Crist',
    image_url: 'https://cdn.fakercloud.com/avatars/plasticine_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 0.7,
    rating: 4,
    super_powers: ['Social Media', 'JavaScript'],
    technologies: [
      'Redux.js',
      'Vue.js',
      'Meteor.js',
      'Social Media',
      'Express.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 59,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Charles',
    last_name: 'Kris',
    image_url: 'https://cdn.fakercloud.com/avatars/ddggccaa_128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 1.6,
    rating: 4,
    super_powers: ['Vue.js', 'Web Design'],
    technologies: [
      'Gulp.js',
      'ASP.NET Web API',
      'Web Video',
      'Ext JS',
      'Web Services API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 60,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Kacie',
    last_name: 'Breitenberg',
    image_url: 'https://cdn.fakercloud.com/avatars/wintopia_128.jpg',
    country_code: 'PT',
    job_position: 'Back End Developer',
    years_of_experience: 9.3,
    rating: 4,
    super_powers: ['JSON', 'Jakarta EE'],
    technologies: [
      'D3.js',
      'Web Services API',
      'Web 2.0',
      'Web Video',
      'JavaScript',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 61,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Connor',
    last_name: 'Aufderhar',
    image_url: 'https://cdn.fakercloud.com/avatars/teeragit_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 4.6,
    rating: 5,
    super_powers: ['JSON', 'AngularJS'],
    technologies: [
      'ASP.NET Web API',
      'J2EE Web Services',
      'D3.js',
      'Redux.js',
      'Web Video',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 62,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Erica',
    last_name: 'Collins',
    image_url: 'https://cdn.fakercloud.com/avatars/marcusgorillius_128.jpg',
    country_code: 'PT',
    job_position: 'Back End Developer',
    years_of_experience: 2,
    rating: 5,
    super_powers: ['Web Services', 'Web Services API'],
    technologies: [
      'Web Analytics',
      'Handlebars.js',
      'Redux.js',
      'JavaScript',
      'React.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 63,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Timmothy',
    last_name: 'Heidenreich',
    image_url: 'https://cdn.fakercloud.com/avatars/jennyyo_128.jpg',
    country_code: 'PT',
    job_position: 'Front End Developer',
    years_of_experience: 3.8,
    rating: 3,
    super_powers: ['Social Media', 'Backbone.js'],
    technologies: [
      'Web Video',
      'Web Applications',
      'Web Services API',
      'Jakarta EE',
      'WebLogic',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 64,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Name',
    last_name: 'Cummings',
    image_url: 'https://cdn.fakercloud.com/avatars/jeremyworboys_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 3.7,
    rating: 3,
    super_powers: ['JavaScript', 'Redux.js'],
    technologies: [
      'AngularJS',
      'Ext JS',
      'Web Design',
      'ASP.NET Web API',
      'Vue.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 65,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Blaze',
    last_name: 'Simonis',
    image_url: 'https://cdn.fakercloud.com/avatars/rangafangs_128.jpg',
    country_code: 'PT',
    job_position: 'Web Developer',
    years_of_experience: 1.1,
    rating: 4,
    super_powers: ['Ext JS', 'J2EE Web Services'],
    technologies: [
      'Jakarta EE',
      'WebLogic',
      'Vue.js',
      'ASP.NET Web API',
      'Require.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 66,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Baylee',
    last_name: 'Miller',
    image_url: 'https://cdn.fakercloud.com/avatars/simobenso_128.jpg',
    country_code: 'PT',
    job_position: 'Systems Analyst',
    years_of_experience: 5,
    rating: 3,
    super_powers: ['Web Services API', 'Redux.js'],
    technologies: [
      'Web Applications',
      'Web Services',
      'AngularJS',
      'Vue.js',
      'J2EE Web Services',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 67,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Jerrod',
    last_name: 'Bailey',
    image_url: 'https://cdn.fakercloud.com/avatars/charliegann_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 4.9,
    rating: 5,
    super_powers: ['D3.js', 'Redux.js'],
    technologies: [
      'Bootstrap',
      'Redux.js',
      'Web 2.0',
      'Backbone.js',
      'ASP.NET Web API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 68,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Miles',
    last_name: 'Boehm',
    image_url: 'https://cdn.fakercloud.com/avatars/marshallchen__128.jpg',
    country_code: 'PT',
    job_position: 'Systems Analyst',
    years_of_experience: 0.1,
    rating: 5,
    super_powers: ['Express.js', 'WebLogic'],
    technologies: [
      'Gulp.js',
      'Social Media',
      'AngularJS',
      'Web Development',
      'Express.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 69,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Manuel',
    last_name: 'Ullrich',
    image_url: 'https://cdn.fakercloud.com/avatars/anasnakawa_128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 8.8,
    rating: 5,
    super_powers: ['Gulp.js', 'Web Services API'],
    technologies: [
      'Redux.js',
      'Web Video',
      'Handlebars.js',
      'Jakarta EE',
      'Meteor.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 70,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Marguerite',
    last_name: 'Ratke',
    image_url: 'https://cdn.fakercloud.com/avatars/themrdave_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 2.2,
    rating: 3,
    super_powers: ['D3.js', 'Node.js'],
    technologies: [
      'Web Services',
      'Redux.js',
      'Handlebars.js',
      'Jakarta EE',
      'AngularJS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 71,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Chris',
    last_name: 'Botsford',
    image_url: 'https://cdn.fakercloud.com/avatars/michalhron_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 3.1,
    rating: 4,
    super_powers: ['Handlebars.js', 'React.js'],
    technologies: [
      'Vue.js',
      'D3.js',
      'WebLogic',
      'Web Services API',
      'ASP.NET Web API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 72,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Madelyn',
    last_name: 'Champlin',
    image_url: 'https://cdn.fakercloud.com/avatars/lepinski_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 2.9,
    rating: 4,
    super_powers: ['Web Analytics', 'Redux.js'],
    technologies: [
      'JavaScript',
      'Jakarta EE',
      'Ext JS',
      'ASP.NET Web API',
      'React.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 73,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Jeromy',
    last_name: 'Lindgren',
    image_url: 'https://cdn.fakercloud.com/avatars/jerrybai1907_128.jpg',
    country_code: 'PT',
    job_position: 'IT Manager',
    years_of_experience: 3.2,
    rating: 3,
    super_powers: ['Web Applications', 'Express.js'],
    technologies: [
      'Web Development',
      'Gulp.js',
      'Social Media',
      'Web Video',
      'Ext JS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 74,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Macie',
    last_name: 'Bergnaum',
    image_url: 'https://cdn.fakercloud.com/avatars/adamnac_128.jpg',
    country_code: 'PT',
    job_position: 'Full Stack Developer',
    years_of_experience: 4.9,
    rating: 5,
    super_powers: ['Web Analytics', 'React.js'],
    technologies: [
      'Meteor.js',
      'Node.js',
      'JSON',
      'Web Applications',
      'Express.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 75,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Domenick',
    last_name: 'Koch',
    image_url: 'https://cdn.fakercloud.com/avatars/mirfanqureshi_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 0.7,
    rating: 3,
    super_powers: ['Ext JS', 'Social Media'],
    technologies: [
      'Express.js',
      'WebLogic',
      'D3.js',
      'Backbone.js',
      'Web Services API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 76,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Meda',
    last_name: 'Bayer',
    image_url: 'https://cdn.fakercloud.com/avatars/ademilter_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 9.1,
    rating: 5,
    super_powers: ['Ext JS', 'Web Applications'],
    technologies: [
      'Bootstrap',
      'Web Development',
      'Web Analytics',
      'Handlebars.js',
      'Web Applications',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 77,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Christelle',
    last_name: 'Jones',
    image_url: 'https://cdn.fakercloud.com/avatars/iamkarna_128.jpg',
    country_code: 'PT',
    job_position: 'Front End Developer',
    years_of_experience: 8.3,
    rating: 4,
    super_powers: ['Vue.js', 'Jakarta EE'],
    technologies: [
      'Meteor.js',
      'Web Video',
      'Web Analytics',
      'Web 2.0',
      'ASP.NET Web API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 78,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Martin',
    last_name: 'Braun',
    image_url: 'https://cdn.fakercloud.com/avatars/iamglimy_128.jpg',
    country_code: 'PT',
    job_position: 'Back End Developer',
    years_of_experience: 8.4,
    rating: 4,
    super_powers: ['Gulp.js', 'Web Applications'],
    technologies: [
      'Web 2.0',
      'JavaScript',
      'Express.js',
      'Node.js',
      'J2EE Web Services',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 79,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Amos',
    last_name: 'Padberg',
    image_url: 'https://cdn.fakercloud.com/avatars/bertboerland_128.jpg',
    country_code: 'PT',
    job_position: 'Software Developer',
    years_of_experience: 9.1,
    rating: 4,
    super_powers: ['Web Design', 'JSON'],
    technologies: [
      'Backbone.js',
      'Require.js',
      'J2EE Web Services',
      'Web Services',
      'Ext JS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 80,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Ezequiel',
    last_name: 'Rohan',
    image_url: 'https://cdn.fakercloud.com/avatars/scrapdnb_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud Architect',
    years_of_experience: 6.9,
    rating: 5,
    super_powers: ['Web Design', 'Web Video'],
    technologies: [
      'Web Applications',
      'Social Media',
      'Redux.js',
      'Jakarta EE',
      'Web Video',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 81,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Neoma',
    last_name: 'McClure',
    image_url: 'https://cdn.fakercloud.com/avatars/brenton_clarke_128.jpg',
    country_code: 'PT',
    job_position: 'IT Manager',
    years_of_experience: 1.1,
    rating: 5,
    super_powers: ['Web Services API', 'Web Development'],
    technologies: [
      'Bootstrap',
      'Vue.js',
      'Require.js',
      'WebLogic',
      'Web Applications',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 82,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Karli',
    last_name: 'Christiansen',
    image_url: 'https://cdn.fakercloud.com/avatars/BenouarradeM_128.jpg',
    country_code: 'PT',
    job_position: 'Software Engineer',
    years_of_experience: 6.3,
    rating: 4,
    super_powers: ['React.js', 'Meteor.js'],
    technologies: [
      'Require.js',
      'AngularJS',
      'JSON',
      'Social Media',
      'ASP.NET Web API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 83,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Emile',
    last_name: 'Spencer',
    image_url: 'https://cdn.fakercloud.com/avatars/kazaky999_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 2,
    rating: 4,
    super_powers: ['Social Media', 'Ember.js'],
    technologies: [
      'Ext JS',
      'ASP.NET Web API',
      'Web Analytics',
      'Express.js',
      'Web 2.0',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 84,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Maiya',
    last_name: 'Erdman',
    image_url: 'https://cdn.fakercloud.com/avatars/serefka_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 2.3,
    rating: 3,
    super_powers: ['Node.js', 'D3.js'],
    technologies: ['JSON', 'Social Media', 'Meteor.js', 'D3.js', 'Backbone.js'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 85,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Landen',
    last_name: 'Powlowski',
    image_url: 'https://cdn.fakercloud.com/avatars/traneblow_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud Architect',
    years_of_experience: 7.6,
    rating: 3,
    super_powers: ['Web 2.0', 'Web Services API'],
    technologies: ['Ext JS', 'Web 2.0', 'Gulp.js', 'Meteor.js', 'Web Video'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 86,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Shanie',
    last_name: 'Lueilwitz',
    image_url: 'https://cdn.fakercloud.com/avatars/josevnclch_128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 1,
    rating: 4,
    super_powers: ['Web Development', 'D3.js'],
    technologies: [
      'Web Services API',
      'Jakarta EE',
      'Bootstrap',
      'AngularJS',
      'WebLogic',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 87,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Julia',
    last_name: 'Ankunding',
    image_url: 'https://cdn.fakercloud.com/avatars/andrewofficer_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 4,
    rating: 3,
    super_powers: ['Meteor.js', 'Ext JS'],
    technologies: [
      'ASP.NET Web API',
      'WebLogic',
      'Web Services API',
      'Social Media',
      'D3.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 88,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Darian',
    last_name: 'Sauer',
    image_url: 'https://cdn.fakercloud.com/avatars/mirfanqureshi_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud Architect',
    years_of_experience: 3.7,
    rating: 5,
    super_powers: ['WebLogic', 'Vue.js'],
    technologies: [
      'JSON',
      'Handlebars.js',
      'Require.js',
      'ASP.NET Web API',
      'Ext JS',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 89,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Flo',
    last_name: 'Spencer',
    image_url: 'https://cdn.fakercloud.com/avatars/opnsrce_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 7.3,
    rating: 4,
    super_powers: ['J2EE Web Services', 'ASP.NET Web API'],
    technologies: [
      'Web Design',
      'Web 2.0',
      'JavaScript',
      'Web Video',
      'Node.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 90,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Parker',
    last_name: 'Ward',
    image_url: 'https://cdn.fakercloud.com/avatars/dev_essentials_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud System Engineer',
    years_of_experience: 5.5,
    rating: 3,
    super_powers: ['Bootstrap', 'JSON'],
    technologies: [
      'Require.js',
      'Web Analytics',
      'JSON',
      'Ext JS',
      'ASP.NET Web API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 91,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Dandre',
    last_name: 'Schroeder',
    image_url: 'https://cdn.fakercloud.com/avatars/bergmartin_128.jpg',
    country_code: 'PT',
    job_position: 'Back End Developer',
    years_of_experience: 4.5,
    rating: 4,
    super_powers: ['Backbone.js', 'Require.js'],
    technologies: [
      'Web Applications',
      'Web 2.0',
      'Social Media',
      'Ext JS',
      'Web Video',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 92,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Lenny',
    last_name: 'Jaskolski',
    image_url: 'https://cdn.fakercloud.com/avatars/gabrielizalo_128.jpg',
    country_code: 'PT',
    job_position: 'Software Architect',
    years_of_experience: 5.7,
    rating: 3,
    super_powers: ['Redux.js', 'Web Development'],
    technologies: [
      'Jakarta EE',
      'Web Services API',
      'Ext JS',
      'Web Applications',
      'Bootstrap',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 93,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Carolanne',
    last_name: 'Hintz',
    image_url: 'https://cdn.fakercloud.com/avatars/iamsteffen_128.jpg',
    country_code: 'PT',
    job_position: 'Web Administrator',
    years_of_experience: 7.7,
    rating: 5,
    super_powers: ['Social Media', 'Web 2.0'],
    technologies: [
      'Web Services',
      'JSON',
      'Ember.js',
      'Backbone.js',
      'Web Development',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 94,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Destini',
    last_name: 'Gerhold',
    image_url: 'https://cdn.fakercloud.com/avatars/bobwassermann_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 5.7,
    rating: 4,
    super_powers: ['JSON', 'Handlebars.js'],
    technologies: [
      'React.js',
      'JavaScript',
      'Express.js',
      'J2EE Web Services',
      'Web Design',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 95,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Hailee',
    last_name: 'Swaniawski',
    image_url: 'https://cdn.fakercloud.com/avatars/omnizya_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud System Engineer',
    years_of_experience: 3.1,
    rating: 3,
    super_powers: ['WebLogic', 'Gulp.js'],
    technologies: [
      'Web Video',
      'AngularJS',
      'Web Development',
      'Redux.js',
      'Web Services API',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 96,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Dana',
    last_name: 'Schneider',
    image_url: 'https://cdn.fakercloud.com/avatars/wikiziner_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud Architect',
    years_of_experience: 4.3,
    rating: 5,
    super_powers: ['Web Design', 'Backbone.js'],
    technologies: [
      'Bootstrap',
      'Social Media',
      'Express.js',
      'Vue.js',
      'Ember.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 97,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Gino',
    last_name: 'Lubowitz',
    image_url: 'https://cdn.fakercloud.com/avatars/maximsorokin_128.jpg',
    country_code: 'PT',
    job_position: 'Cloud Architect',
    years_of_experience: 0.5,
    rating: 3,
    super_powers: ['Gulp.js', 'Backbone.js'],
    technologies: [
      'Web 2.0',
      'Backbone.js',
      'Web Analytics',
      'Redux.js',
      'React.js',
    ],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 98,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
  {
    first_name: 'Jaime',
    last_name: 'Kreiger',
    image_url: 'https://cdn.fakercloud.com/avatars/edgarchris99_128.jpg',
    country_code: 'PT',
    job_position: 'IT Support Specialist',
    years_of_experience: 8,
    rating: 5,
    super_powers: ['Express.js', 'Ember.js'],
    technologies: ['Gulp.js', 'Bootstrap', 'Node.js', 'Jakarta EE', 'Web 2.0'],
    linked_in_url: 'https://www.linkedin.com/',
    github_url: 'https://github.com/',
    id: 99,
    bio: 'Today, not much has changed. I’m still the first point of call for technical issues. The difference is I now also develop innovative software to solve the problems of multinational companies. One of my most recent projects involved designing and rolling-out a new piece of software to optimise the efficiency of holiday bookings. This contributed to a reduction in staff numbers and 12% increase in travel bookings.',
  },
];
export default developers;
