const technologies = [
  'Node.js',
  'React.js',
  'JSON',
  'Vue.js',
  'Express.js',
  'Redux.js',
  'JavaScript',
  'Gulp.js',
  'Backbone.js',
  'Ext JS',
  'D3.js',
  'Ember.js',
  'Meteor.js',
  'AngularJS',
  'Jakarta EE',
  'Handlebars.js',
  'Bootstrap',
  'Require.js',
  'Web Development',
  'Web Design',
  'Web Services',
  'Web Applications',
  'Web Analytics',
  'Social Media',
  'Web 2.0',
  'ASP.NET Web API',
  'Web Video',
  'J2EE Web Services',
  'WebLogic',
  'Web Services API',
];

export default technologies;
